name: Scraping CMRL site
on:
    schedule:
        - cron: "10 18 * * *"
    workflow_dispatch:

jobs:
  Scrape-cmrl-api:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          
      - name: Install the project
        run: uv sync --all-extras --dev

      - name: "Run main.py"
        run: uv run main.py
