name: Scraping CMRL site
on:
    schedule:
        - cron: "40 18 * * *"
    workflow_dispatch:

jobs:
  Scrape-cmrl-api:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          
      - name: Install the project
        run: uv sync --all-extras --dev

      - name: "Run main.py"
        run: uv run main.py
        
      - name: Initiate Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
    
      - name: Commit changes
        run: |
          export TZ=Asia/Kolkata
          CURRENT_DATE=$(date '+%d-%m-%Y')
          git add .
          git commit -m "Update scraped data on $CURRENT_DATE [skip ci]"
          git push origin

